# Generated by Django 4.2.23 on 2025-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.RemoveField(
            model_name="book",
            name="pages",
        ),
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
