# Generated by Django 4.2.23 on 2025-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_book_id_remove_book_pages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.AddField(
            model_name="book",
            name="image_url_m",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="image_url_s",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
